spring:
  application:
    name: qianyu-single-boot
  profiles:
    active: @spring.profiles.active@
    group:
      dev: jdbc,redis,sms,im,storage,login
  # 使用虚拟线程
  threads:
    virtual:
      enabled: true
  # 加载配置。nacos 配置中心相关配置
  config:
    import:
    - optional:nacos:${spring.application.name}.yaml
    - optional:nacos:application-jdbc.yaml
    - optional:nacos:application-redis.yaml
    - optional:nacos:application-sms.yaml
    - optional:nacos:application-im.yaml
    - optional:nacos:application-storage.yaml
    - optional:nacos:application-login.yaml
  cloud:
    nacos:
      config:
        namespace: @nacos.namespace@
        server-addr: ${NACOS_SERVER_ADDR}
        group: qianyu-single-boot


# 单体服务不使用注册中心。
dubbo:
  protocol:
    name: dubbo
    port: 0
  registry:
    address: N/A   # 不使用注册中心

---
## 开发环境配置，包含所有模块的配置，方便本地开发调试
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    nacos:
      config:
        enabled: off