spring:
  application:
    name: qianyu-single-boot
  profiles:
    active: @spring.profiles.active@
  # 使用虚拟线程
  threads:
    virtual:
      enabled: true
  # 加载配置。nacos 配置中心相关配置
  config:
    import:
    - optional:nacos:${spring.application.name}.yaml
    - optional:nacos:application-jdbc.yaml
    - optional:nacos:application-redis.yaml
    - optional:nacos:application-sms.yaml
    - optional:nacos:application-im.yaml
    - optional:nacos:application-storage.yaml
    - optional:nacos:application-login.yaml
  cloud:
    nacos:
      config:
        namespace: @nacos.namespace@
        server-addr: ${NACOS_SERVER_ADDR}
        group: qianyu-single-boot


# 单体服务不使用注册中心。
dubbo:
  protocol:
    name: dubbo
    port: 0
  registry:
    address: N/A   # 不使用注册中心

---
## 本地环境配置，包含最小化的配置，方便本地快速启动; 可通过 nacos 快速启动;
spring:
  config:
    activate:
      on-profile: local

---
## 开发环境配置，包含所有模块的配置，方便本地开发调试
spring:
  config:
    activate:
      on-profile: dev
  profiles:
    include:
    - jdbc
    - redis
    - sms
    - im
    - storage
    - login
  cloud:
    nacos:
      config:
        enabled: off

---
spring:
  config:
    activate:
      on-profile: test
  cloud:
    nacos:
      config:
        namespace: qianyu-test
        server-addr: ${NACOS_SERVER_ADDR}
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    nacos:
      config:
        namespace: qianyu-prod
        server-addr: ${NACOS_SERVER_ADDR}
