spring:
  application:
    name: qianyu-single-boot
  profiles:
    # mvn compile -Plocal 会将 @spring.profiles.active@ 替换为 local
    # 支持 -Pprod, -Ptest , -Plocal, -Pdev
    active: @spring.profiles.active@
    group:
      # dev 环境不适用nacos, 直接引入各模块的配置文件，方便本地开发调试。其他环境使用nacos配置中心统一管理配置。
      dev: jdbc,redis,sms,im,storage,login,mall
      local: mall
  cloud:
    nacos:
      config:
        # mvn compile -Plocal 会将 @nacos.namespace@ 替换为 qianyu-local
        # 如果修改 在 qianyu-boot/pom.xml 中修改
        namespace: @nacos.namespace@
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        group: qianyu-single-boot
  # 加载配置。nacos 配置中心相关配置
  config:
    import:
    - optional:nacos:${spring.application.name}.yaml
    - optional:nacos:application-jdbc.yaml
    - optional:nacos:application-redis.yaml
    - optional:nacos:application-sms.yaml
    - optional:nacos:application-im.yaml
    - optional:nacos:application-storage.yaml
    - optional:nacos:application-login.yaml
    - optional:nacos:application-mall.yaml
  # 使用虚拟线程
  threads:
    virtual:
      enabled: true

# 单体服务不使用注册中心。
dubbo:
  protocol:
    name: dubbo
    port: 0
  registry:
    address: N/A   # 不使用注册中心

---
## DEV 环境配置，包含所有模块的配置， 不启动环境变量中的 nacos 配置中心相关配置，方便本地开发调试。
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    nacos:
      config:
        enabled: off