<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.clmcat.app</groupId>
        <artifactId>qianyu-service</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>qianyu-dependencies-service</artifactId>
    <description>全部service依赖</description>
    <packaging>pom</packaging>
    <dependencies>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-user-service</artifactId>
            <version>${project.qianyu.version}</version>
        </dependency>
    </dependencies>
</project>