<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.clmcat.app</groupId>
    <artifactId>qianyu-app-service</artifactId>
    <version>1.0-SNAPSHOT</version>

    <packaging>pom</packaging>
    <modules>
        <module>qianyu-api</module>
        <module>qianyu-core</module>
        <module>qianyu-service</module>
        <module>qianyu-boot</module>
        <module>qianyu-dependencies</module>
    </modules>

    <parent>
        <groupId>com.clmcat.framework</groupId>
        <artifactId>clmcat-framework</artifactId>
        <version>1.1.0</version>
    </parent>

    <properties>
        <project.qianyu.version>1.0-SNAPSHOT</project.qianyu.version>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-service</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-api</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-core</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-dependencies</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.mybatis-flex</groupId>
                <artifactId>mybatis-flex-spring-boot3-starter</artifactId>
                <version>1.11.7</version>
            </dependency>
            <dependency>
                <groupId>com.mybatis-flex</groupId>
                <artifactId>mybatis-flex-processor</artifactId>
                <version>1.11.7</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>com.googlecode.libphonenumber</groupId>
                <artifactId>libphonenumber</artifactId>
                <version>8.13.55</version>
            </dependency>

            <dependency>
                <groupId>com.github.kstyrc</groupId>
                <artifactId>embedded-redis</artifactId>
                <version>0.6</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>