<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.clmcat.app</groupId>
        <artifactId>qianyu-app-service</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>qianyu-api</artifactId>
    <packaging>pom</packaging>
    <description>API接口定义模块</description>
    <modules>
        <module>qianyu-user-api</module>
        <module>qianyu-core-api</module>
        <module>qianyu-social-api</module>
        <module>qianyu-live-api</module>
        <module>qianyu-gift-api</module>
        <module>qianyu-im-api</module>
        <module>qianyu-mail-api</module>
        <module>qianyu-storage-api</module>
        <module>qianyu-payment-api</module>
        <module>qianyu-notification-api</module>
        <module>qianyu-review-api</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-core-api</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-user-api</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-social-api</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-live-api</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-gift-api</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-im-api</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-mail-api</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-storage-api</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-payment-api</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-notification-api</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-review-api</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>