<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.clmcat.app</groupId>
        <artifactId>qianyu-service</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>qianyu-storage-service</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-web-dependencies</artifactId>
        </dependency>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-storage-api</artifactId>
        </dependency>

        <!-- 阿里云 OSS SDK -->
        <dependency>
            <groupId>com.aliyun.oss</groupId>
            <artifactId>aliyun-sdk-oss</artifactId>
            <version>3.17.4</version>
        </dependency>

        <!-- 腾讯云 COS SDK -->
        <dependency>
            <groupId>com.qcloud</groupId>
            <artifactId>cos_api</artifactId>
            <version>5.6.213</version>
        </dependency>
    </dependencies>

</project>
