<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.clmcat.app</groupId>
        <artifactId>qianyu-service</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>qianyu-im-service</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-web-dependencies</artifactId>
        </dependency>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-im-api</artifactId>
        </dependency>

        <!-- 腾讯云 IM UserSig 生成 SDK -->
        <dependency>
            <groupId>com.github.tencentyun</groupId>
            <artifactId>tls-sig-api-v2</artifactId>
            <version>2.0</version>
        </dependency>

<!--        &lt;!&ndash; 单元测试 (JUnit 5 + Mockito) &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>org.springframework.boot</groupId>-->
<!--            <artifactId>spring-boot-starter-test</artifactId>-->
<!--            <scope>test</scope>-->
<!--        </dependency>-->
    </dependencies>

</project>