<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.clmcat.app</groupId>
        <artifactId>qianyu-app-service</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>qianyu-service</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>qianyu-user-service</module>
        <module>qianyu-social-service</module>
        <module>qianyu-live-service</module>
        <module>qianyu-gift-service</module>
        <module>qianyu-im-service</module>
        <module>qianyu-mall-service</module>
        <module>qianyu-storage-service</module>
        <module>qianyu-payment-service</module>
        <module>qianyu-notification-service</module>
        <module>qianyu-review-service</module>
        <module>qianyu-search-service</module>
    </modules>

    <dependencies>
        <!-- 直接引入全部API依赖，为了快速开发。 -->
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-allapi-dependencies</artifactId>
        </dependency>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-core</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-user-service</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-social-service</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-live-service</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-gift-service</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-im-service</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-mall-service</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-storage-service</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-payment-service</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-notification-service</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-review-service</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-search-service</artifactId>
                <version>${project.qianyu.version}</version>
            </dependency>

            <!-- qianyu-api -->
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-api</artifactId>
                <version>${project.qianyu.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>

            <!-- 基础依赖 -->
            <dependency>
                <groupId>com.clmcat.app</groupId>
                <artifactId>qianyu-dependencies</artifactId>
                <version>${project.qianyu.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>