<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.clmcat.app</groupId>
        <artifactId>qianyu-app-service</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>qianyu-allapi-dependencies</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-core-api</artifactId>
            <version>${project.qianyu.version}</version>
        </dependency>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-user-api</artifactId>
            <version>${project.qianyu.version}</version>
        </dependency>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-social-api</artifactId>
            <version>${project.qianyu.version}</version>
        </dependency>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-live-api</artifactId>
            <version>${project.qianyu.version}</version>
        </dependency>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-gift-api</artifactId>
            <version>${project.qianyu.version}</version>
        </dependency>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-im-api</artifactId>
            <version>${project.qianyu.version}</version>
        </dependency>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-mall-api</artifactId>
            <version>${project.qianyu.version}</version>
        </dependency>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-storage-api</artifactId>
            <version>${project.qianyu.version}</version>
        </dependency>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-payment-api</artifactId>
            <version>${project.qianyu.version}</version>
        </dependency>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-notification-api</artifactId>
            <version>${project.qianyu.version}</version>
        </dependency>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-review-api</artifactId>
            <version>${project.qianyu.version}</version>
        </dependency>
        <dependency>
            <groupId>com.clmcat.app</groupId>
            <artifactId>qianyu-center-api</artifactId>
            <version>${project.qianyu.version}</version>
        </dependency>
    </dependencies>
</project>